services:
  postgres:
    container_name: job_management_postgres
    image: postgres
    ports:
      - "5433:5432"  # 5433
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=job_management